In [2]:
from google.colab import files

uploaded = files.upload()

Saving Copy of swiggy.xlsx to Copy of swiggy.xlsx

In [3]:
from google.colab import files

uploaded = files.upload()

Saving Copy of zomato_restaurants_in_India.xlsx to Copy of zomato_restaurants_in_India.xlsx

In [4]:
import pandas as pd

zomato = pd.read_excel("/content/Copy of zomato_restaurants_in_India.xlsx")
swiggy = pd.read_excel("/content/Copy of swiggy.xlsx")
print(zomato.shape)
print(swiggy.shape)

print(zomato.columns.tolist())
print(swiggy.columns.tolist())

(211944, 26)
(8680, 10)
['res_id', 'name', 'establishment', 'url', 'address', 'city', 'city_id', 'locality', 'latitude', 'longitude', 'zipcode', 'country_id', 'locality_verbose', 'cuisines', 'timings', 'average_cost_for_two', 'price_range', 'currency', 'highlights', 'aggregate_rating', 'rating_text', 'votes', 'photo_count', 'opentable_support', 'delivery', 'takeaway']
['ID', 'Area', 'City', 'Restaurant', 'Price', 'Avg ratings', 'Total ratings', 'Food type', 'Address', 'Delivery time']

In [5]:
zomato.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211944 entries, 0 to 211943
Data columns (total 26 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   res_id                211944 non-null  int64
 1   name                  211944 non-null  object
 2   establishment         211944 non-null  object
 3   url                   211944 non-null  object
 4   address               211810 non-null  object
 5   city                  211944 non-null  object
 6   city_id               211944 non-null  int64
 7   locality              211944 non-null  object
 8   latitude              211944 non-null  float64
 9   longitude             211944 non-null  float64
 10  zipcode               48757 non-null   object
 11  country_id            211944 non-null  int64
 12  locality_verbose      211944 non-null  object
 13  cuisines              210553 non-null  object
 14  timings               208070 non-null  object
 15  average_cost_for_two  211944 non-null  int64
 16  price_range           211944 non-null  int64
 17  currency              211944 non-null  object
 18  highlights            211944 non-null  object
 19  aggregate_rating      211944 non-null  float64
 20  rating_text           211944 non-null  object
 21  votes                 211944 non-null  int64
 22  photo_count           211944 non-null  int64
 23  opentable_support     211896 non-null  float64
 24  delivery              211944 non-null  int64
 25  takeaway              211944 non-null  int64
dtypes: float64(4), int64(9), object(13)
memory usage: 42.0+ MB

In [6]:
print(zomato.columns.tolist())

['res_id', 'name', 'establishment', 'url', 'address', 'city', 'city_id', 'locality', 'latitude', 'longitude', 'zipcode', 'country_id', 'locality_verbose', 'cuisines', 'timings', 'average_cost_for_two', 'price_range', 'currency', 'highlights', 'aggregate_rating', 'rating_text', 'votes', 'photo_count', 'opentable_support', 'delivery', 'takeaway']

In [7]:
zomato.isnull().sum().sort_values(ascending=False)

zipcode                 163187
timings                   3874
cuisines                  1391
address                    134
opentable_support           48
city                         0
name                         0
establishment                0
url                          0
res_id                       0
longitude                    0
latitude                     0
locality                     0
city_id                      0
locality_verbose             0
average_cost_for_two         0
price_range                  0
country_id                   0
currency                     0
highlights                   0
rating_text                  0
aggregate_rating             0
votes                        0
photo_count                  0
delivery                     0
takeaway                     0
dtype: int64

In [8]:
zomato["timings"] = zomato["timings"].fillna("Not Available")

zomato["cuisines"] = zomato["cuisines"].fillna("Unknown")

In [9]:
zomato.isnull().sum().sum()

np.int64(163369)

In [11]:
# Drop columns with little analytical value

zomato = zomato.drop(
    columns=[
        'url',
        'address',
        'zipcode',
        'opentable_support'
    ],
    errors='ignore'
)

# Fill remaining missing values

zomato['cuisines'] = zomato['cuisines'].fillna('Unknown')

zomato['timings'] = zomato['timings'].fillna('Not Available')

In [12]:
zomato.isnull().sum().sum()

np.int64(0)

In [13]:
zomato["cost_category"] = pd.cut(
    zomato["average_cost_for_two"],
    bins=[0,500,1000,2000,100000],
    labels=["Budget","Mid Range","Premium","Luxury"]
)

In [14]:
zomato["cost_category"].value_counts()

cost_category
Budget       135330
Mid Range     46780
Premium       22768
Luxury         4989
Name: count, dtype: int64

In [15]:
zomato["popularity"] = pd.cut(
    zomato["votes"],
    bins=[-1,50,200,1000,1000000],
    labels=["Low","Medium","High","Very High"]
)

In [16]:
zomato["popularity"].value_counts()

popularity
Low          82232
High         57660
Medium       52650
Very High    19399
Name: count, dtype: int64

In [17]:
zomato["aggregate_rating"].describe()

count    211944.000000
mean          3.395937
std           1.283642
min           0.000000
25%           3.300000
50%           3.800000
75%           4.100000
max           4.900000
Name: aggregate_rating, dtype: float64

In [18]:
swiggy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8680 entries, 0 to 8679
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             8680 non-null   int64
 1   Area           8680 non-null   object
 2   City           8680 non-null   object
 3   Restaurant     8680 non-null   object
 4   Price          8680 non-null   int64
 5   Avg ratings    8680 non-null   float64
 6   Total ratings  8680 non-null   int64
 7   Food type      8680 non-null   object
 8   Address        8680 non-null   object
 9   Delivery time  8680 non-null   int64
dtypes: float64(1), int64(4), object(5)
memory usage: 678.3+ KB

In [19]:
swiggy.isnull().sum()

ID               0
Area             0
City             0
Restaurant       0
Price            0
Avg ratings      0
Total ratings    0
Food type        0
Address          0
Delivery time    0
dtype: int64

In [20]:
swiggy.columns = (
    swiggy.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [21]:
swiggy.columns

Index(['id', 'area', 'city', 'restaurant', 'price', 'avg_ratings',
       'total_ratings', 'food_type', 'address', 'delivery_time'],
      dtype='object')

In [22]:
swiggy["id"].duplicated().sum()

np.int64(0)

In [23]:
swiggy.drop_duplicates(
    subset="id",
    inplace=True
)

In [24]:
swiggy["price_category"] = pd.cut(
    swiggy["price"],
    bins=[0,200,400,700,10000],
    labels=[
        "Budget",
        "Mid Range",
        "Premium",
        "Luxury"
    ]
)

In [25]:
swiggy["price_category"].value_counts()

price_category
Mid Range    4137
Budget       2751
Premium      1204
Luxury        583
Name: count, dtype: int64

In [26]:
swiggy["delivery_category"] = pd.cut(
    swiggy["delivery_time"],
    bins=[0,30,45,60,500],
    labels=[
        "Fast",
        "Normal",
        "Slow",
        "Very Slow"
    ]
)

In [27]:
swiggy["rating_category"] = pd.cut(
    swiggy["avg_ratings"],
    bins=[0,2,3,4,5],
    labels=[
        "Poor",
        "Average",
        "Good",
        "Excellent"
    ]
)

In [28]:
swiggy["rating_category"] = pd.cut(
    swiggy["avg_ratings"],
    bins=[0,2,3,4,5],
    labels=[
        "Poor",
        "Average",
        "Good",
        "Excellent"
    ]
)

In [29]:
zomato.to_csv(
    "zomato_clean.csv",
    index=False
)

swiggy.to_csv(
    "swiggy_clean.csv",
    index=False
)

In [30]:
from google.colab import files

files.download("zomato_clean.csv")
files.download("swiggy_clean.csv")